"use client";
import {AnimatePresence,motion} from "framer-motion";
import Image from "next/image";
import Link from "next/link";
import {ArrowRight,ChevronDown,Package} from "lucide-react";
import {useState} from "react";
import type {Locale} from "@/lib/i18n";
const copy={tr:{title:"Yedek Parçalar",text:"Otomobil, kamyon ve iş makineleri için güvenilir parça çözümlerini keşfedin.",hint:"Fotoğrafa tıklayarak kategori seçin",open:"Kategorileri göster",close:"Kategorileri gizle",items:[["automotive-spare-parts","Otomobil Yedek Parçaları","Binek araçlar için fren, filtre ve motor bileşenleri."],["truck-spare-parts","Kamyon Yedek Parçaları","Ağır ticari araçlar için fren, süspansiyon ve aktarma parçaları."],["heavy-machinery-spare-parts","İş Makinesi Yedek Parçaları","Ekskavatör ve iş makineleri için hidrolik ve aşınma parçaları."]]},en:{title:"Spare Parts",text:"Discover reliable parts solutions for passenger cars, trucks and heavy equipment.",hint:"Click the photo to choose a category",open:"Show categories",close:"Hide categories",items:[["automotive-spare-parts","Automotive Spare Parts","Brake, filtration and engine components for passenger vehicles."],["truck-spare-parts","Truck Spare Parts","Braking, suspension and drivetrain parts for heavy commercial vehicles."],["heavy-machinery-spare-parts","Heavy Machinery Spare Parts","Hydraulic and wear parts for excavators and heavy equipment."]]},es:{title:"Repuestos",text:"Descubra soluciones confiables para automóviles, camiones y maquinaria pesada.",hint:"Haga clic en la foto para elegir una categoría",open:"Ver categorías",close:"Ocultar categorías",items:[["automotive-spare-parts","Repuestos para Automóviles","Componentes de freno, filtración y motor para automóviles."],["truck-spare-parts","Repuestos para Camiones","Piezas de freno, suspensión y transmisión para vehículos pesados."],["heavy-machinery-spare-parts","Repuestos para Maquinaria Pesada","Piezas hidráulicas y de desgaste para maquinaria pesada."]]}} as const;
export function SparePartsHub({locale}:{locale:Locale}){const t=copy[locale];const [open,setOpen]=useState(false);return <section className="mt-20 border-t border-ink/10 pt-12"><div className="mb-8"><p className="eyebrow">{t.title}</p><h2 className="mt-2 text-3xl font-semibold tracking-tight text-ink sm:text-4xl">{t.text}</h2></div><button type="button" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label={open?t.close:t.open} className="group relative block min-h-[22rem] w-full overflow-hidden rounded-[2rem] text-left shadow-[0_25px_80px_rgba(8,20,39,.14)]"><Image src="/truck-spare-parts.png" alt={t.title} fill priority className="object-cover transition duration-700 group-hover:scale-105"/><span className="absolute inset-0 bg-gradient-to-t from-ink/80 via-ink/10 to-transparent"/><span className="absolute bottom-7 left-7 right-7 flex items-end justify-between gap-4 text-white"><span><span className="block text-xs font-semibold uppercase tracking-[.22em] text-aqua">{t.hint}</span><span className="mt-2 block text-2xl font-semibold sm:text-3xl">{t.title}</span></span><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-white/15 backdrop-blur transition group-hover:bg-copper"><ChevronDown className={open?"transition rotate-180":"transition"} size={22}/></span></span></button><AnimatePresence initial={false}>{open&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} transition={{duration:.35,ease:"easeOut"}} className="overflow-hidden"><div className="grid gap-4 pt-6 md:grid-cols-3">{t.items.map(([slug,label,desc])=><Link key={slug} href={"/"+locale+"/products/"+slug} className="group rounded-3xl border border-ink/10 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-ocean/25 hover:shadow-lg"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-mist text-ocean"><Package size={20}/></span><h3 className="mt-5 text-lg font-semibold">{label}</h3><p className="mt-3 text-sm leading-6 text-ink/55">{desc}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-ocean">{locale==="tr"?"Detayları incele":locale==="es"?"Ver detalles":"View details"}<ArrowRight size={15}/></span></Link>)}</div></motion.div>}</AnimatePresence></section>}
