import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { products } from "@/lib/data";
import { isLocale, localizeCountry } from "@/lib/i18n";
import { SITE_URL } from "@/lib/seo";

const copy={
  tr:{support:"Ticaret desteği",supportText:"tedarik, doğrulama, lojistik ve dokümantasyon.",availability:"Uygunluk",availabilityText:"üretici kapasitesine ve hedef ülke gereksinimlerine bağlıdır.",terms:"Ticari koşullar",termsText:"ihtiyaç değerlendirmesinden sonra sunulur.",cta:"Size özel teklif isteyin",details:"Tedarik kapsamı",detailsText:"Üretici araştırması, ürün ve belge kontrolü, teklif karşılaştırması ve sevkiyat planlaması ihtiyaca göre koordine edilir.",packaging:"Ambalaj ve sipariş",packagingText:"Ambalaj türü, minimum sipariş miktarı ve termin süresi üreticiye ve teknik gereksinimlere göre teyit edilir.",compliance:"Kalite ve uygunluk",complianceText:"Sertifika, test, etiketleme ve hedef ülke mevzuatı sipariş öncesinde ürün bazında değerlendirilmelidir.",related:"Benzer fırsatlar",commercial:"Ticari değerlendirme",services:"Hizmetlerimizi inceleyin"},
  en:{support:"Trade support",supportText:"sourcing, verification, logistics and documentation.",availability:"Availability",availabilityText:"subject to producer capacity and destination requirements.",terms:"Commercial terms",termsText:"provided after requirement review.",cta:"Request a tailored quote",details:"Sourcing scope",detailsText:"Producer research, product and document checks, quotation comparison and shipment planning are coordinated to match the requirement.",packaging:"Packaging and orders",packagingText:"Packaging, minimum order quantity and lead time are confirmed according to the producer and technical specification.",compliance:"Quality and compliance",complianceText:"Certificates, testing, labeling and destination rules should be reviewed for the specific product before ordering.",related:"Related opportunities",commercial:"Commercial assessment",services:"Explore our services"},
  es:{support:"Apoyo comercial",supportText:"abastecimiento, verificación, logística y documentación.",availability:"Disponibilidad",availabilityText:"sujeta a capacidad del productor y requisitos del destino.",terms:"Condiciones comerciales",termsText:"se proporcionan tras revisar la necesidad.",cta:"Solicitar cotización personalizada",details:"Alcance de abastecimiento",detailsText:"La búsqueda de productores, revisión de producto y documentos, comparación de ofertas y planificación logística se coordinan según la necesidad.",packaging:"Embalaje y pedidos",packagingText:"Embalaje, pedido mínimo y plazo se confirman según productor y especificación técnica.",compliance:"Calidad y cumplimiento",complianceText:"Certificados, ensayos, etiquetado y normativa de destino deben evaluarse para cada producto antes del pedido.",related:"Oportunidades relacionadas",commercial:"Evaluación comercial",services:"Ver nuestros servicios"}
} as const;

const categories={tr:{Food:"Gıda",Agriculture:"Tarım",Machinery:"Makine",Seafood:"Deniz Ürünleri",Construction:"Yapı",Beverage:"İçecek",Automotive:"Otomotiv",Truck:"Kamyon",HeavyEquipment:"İş Makineleri"},en:{Food:"Food",Agriculture:"Agriculture",Machinery:"Machinery",Seafood:"Seafood",Construction:"Construction",Beverage:"Beverage",Automotive:"Automotive",Truck:"Truck",HeavyEquipment:"Heavy Equipment"},es:{Food:"Alimentos",Agriculture:"Agricultura",Machinery:"Maquinaria",Seafood:"Productos del mar",Construction:"Construcción",Beverage:"Bebidas",Automotive:"Automoción",Truck:"Camiones",HeavyEquipment:"Maquinaria Pesada"}} as const;

const commercialContext:Record<string,{tr:string,en:string,es:string}>={
  "turkish-sunflower-oil":{tr:"Gıda yağlarında ürün tipi, ambalaj formatı, etiketleme, raf ömrü belgeleri ve hedef pazar gereksinimleri teklif öncesinde netleştirilmelidir.",en:"For edible oils, product type, packaging format, labeling, shelf-life documentation and destination requirements should be clarified before quotation.",es:"Para aceites comestibles, conviene definir antes de cotizar el tipo de producto, formato de envase, etiquetado, documentación de vida útil y requisitos del mercado de destino."},
  "chilean-walnuts":{tr:"Ceviz tedarikinde kalite sınıfı, kalibre, hasat dönemi, ambalaj, analiz belgeleri ve sevkiyat koşulları ticari karşılaştırmanın temelini oluşturur.",en:"For walnut sourcing, grade, size, crop period, packaging, analysis documents and shipment conditions are key points for commercial comparison.",es:"En el abastecimiento de nueces, calibre, calidad, temporada de cosecha, embalaje, documentos de análisis y condiciones de envío son puntos clave para comparar ofertas."},
  "industrial-machinery":{tr:"Endüstriyel makine alımlarında teknik şartname, kapasite, elektrik standardı, yedek parça desteği, teslim kapsamı ve kurulum ihtiyacı teklif öncesinde doğrulanmalıdır.",en:"Industrial machinery sourcing should confirm technical specification, capacity, electrical standard, spare-parts support, delivery scope and installation requirements before quotation.",es:"En maquinaria industrial se deben confirmar antes de cotizar la especificación técnica, capacidad, estándar eléctrico, repuestos, alcance de suministro y necesidades de instalación."},
  "chilean-seafood":{tr:"Deniz ürünlerinde ürün formu, işleme yöntemi, soğuk zincir, sağlık belgeleri, ambalaj ve hedef ülke ithalat şartları birlikte değerlendirilmelidir.",en:"Seafood sourcing requires alignment on product form, processing method, cold chain, health documentation, packaging and destination import requirements.",es:"En productos del mar deben evaluarse conjuntamente la presentación, método de proceso, cadena de frío, documentación sanitaria, embalaje y requisitos de importación del destino."},
  "construction-materials":{tr:"Yapı malzemelerinde teknik standart, ölçü, dayanım sınıfı, paketleme, test belgeleri ve proje bazlı miktarlar doğru tedarikçi eşleştirmesi için önemlidir.",en:"For construction materials, technical standard, dimensions, performance class, packaging, test documents and project quantities are important for supplier matching.",es:"Para materiales de construcción, norma técnica, dimensiones, clase de desempeño, embalaje, ensayos y volúmenes del proyecto son importantes para seleccionar proveedores."},
  "chilean-wine-solutions":{tr:"İçecek tedarikinde ürün segmenti, ambalaj, etiket, ihracat belgeleri, hedef pazar mevzuatı ve dağıtım modeli siparişten önce değerlendirilmelidir.",en:"Beverage sourcing should review product segment, packaging, labeling, export documents, destination rules and distribution model before ordering.",es:"En bebidas conviene revisar antes del pedido el segmento de producto, envase, etiquetado, documentos de exportación, normativa de destino y modelo de distribución."},
  "automotive-spare-parts":{tr:"Otomotiv yedek parçalarında araç marka-modeli, parça referansı veya OEM numarası, teknik uyumluluk, adet ve kalite beklentisi doğru teklif için mümkün olduğunca net verilmelidir.",en:"Automotive spare-parts sourcing is more accurate when vehicle make/model, part reference or OEM number, technical compatibility, quantity and quality expectations are clearly specified.",es:"Para cotizar repuestos automotrices con precisión conviene indicar marca/modelo del vehículo, referencia o número OEM, compatibilidad técnica, cantidad y nivel de calidad esperado."},
  "truck-spare-parts":{tr:"Kamyon parçalarında şasi veya OEM referansı, araç konfigürasyonu, parça grubu, miktar ve kullanım şartları eşdeğer ürün riskini azaltmak için teyit edilmelidir.",en:"Truck-parts sourcing should confirm chassis or OEM reference, vehicle configuration, part group, quantity and operating conditions to reduce incorrect-equivalent risk.",es:"En repuestos para camiones conviene confirmar chasis o referencia OEM, configuración del vehículo, grupo de pieza, cantidad y condiciones de uso para reducir errores de equivalencia."},
  "heavy-machinery-spare-parts":{tr:"İş makinesi parçalarında makine marka-modeli, seri numarası, parça numarası, komponent tipi ve çalışma koşulları doğru tedarikçi ve parça eşleştirmesi için kritik girdilerdir.",en:"Heavy-equipment parts sourcing depends on machine make/model, serial number, part number, component type and operating conditions for accurate supplier and part matching.",es:"En repuestos de maquinaria pesada, marca/modelo, número de serie, número de pieza, tipo de componente y condiciones de trabajo son datos clave para una correcta identificación."}
};

type Params={params:Promise<{locale:string,slug:string}>};

const resolveImageUrl=(image:string)=>image.startsWith("http://")||image.startsWith("https://")?image:`${SITE_URL}${image}`;

export async function generateMetadata({params}:Params):Promise<Metadata> {
  const {locale,slug}=await params;
  if(!isLocale(locale)) return {};
  const product=products.find(x=>x.slug===slug);
  if(!product) return {};
  const name=product.names[locale];
  const description=product.desc[locale];
  const canonical=`${SITE_URL}/${locale}/products/${slug}`;
  const title=`${name} | HKO Trade Hub`;
  const imageUrl=resolveImageUrl(product.image);
  return {
    title,
    description,
    alternates:{canonical,languages:{"tr-TR":`${SITE_URL}/tr/products/${slug}`,"en":`${SITE_URL}/en/products/${slug}`,"es-CL":`${SITE_URL}/es/products/${slug}`,"x-default":`${SITE_URL}/en/products/${slug}`}},
    openGraph:{title,description,url:canonical,siteName:"HKO Trade Hub",type:"website",locale:locale==="tr"?"tr_TR":locale==="es"?"es_CL":"en_US",images:[{url:imageUrl,alt:name}]},
    twitter:{card:"summary_large_image",title,description,images:[imageUrl]},
    robots:{index:true,follow:true}
  };
}

export default async function Page({params}:Params) {
  const {locale,slug}=await params;
  if(!isLocale(locale)) notFound();
  const product=products.find(x=>x.slug===slug);
  if(!product) notFound();
  const t=copy[locale],category=categories[locale][product.category as keyof typeof categories.en]||product.category;
  const canonical=`${SITE_URL}/${locale}/products/${slug}`;
  const structuredData={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"HKO Trade Hub",item:`${SITE_URL}/${locale}`},{"@type":"ListItem",position:2,name:locale==="tr"?"Ürünler":locale==="es"?"Productos":"Products",item:`${SITE_URL}/${locale}/products`},{"@type":"ListItem",position:3,name:product.names[locale],item:canonical}]};
  const related=products.filter(item=>item.slug!==slug&&(item.category===product.category||item.origin===product.origin)).slice(0,3);
  const context=commercialContext[slug]?.[locale];
  return <section className="section"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><div className="container-shell"><nav className="mb-8 text-sm text-ink/50"><Link href={`/${locale}`}>HKO Trade Hub</Link> / <Link href={`/${locale}/products`}>{locale==="tr"?"Ürünler":locale==="es"?"Productos":"Products"}</Link></nav><div className="grid gap-12 lg:grid-cols-2"><div className="relative min-h-[480px] overflow-hidden rounded-[2.5rem]"><Image src={product.image} alt={`${product.names[locale]} — ${localizeCountry(product.origin,locale)}`} fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/></div><div className="self-center"><p className="eyebrow">{category} · {localizeCountry(product.origin,locale)}</p><h1 className="heading">{product.names[locale]}</h1><p className="mt-6 text-lg leading-8 text-ink/60">{product.desc[locale]}</p><div className="mt-8 grid gap-3 rounded-3xl bg-sand p-6 text-sm"><p><b>{t.support}:</b> {t.supportText}</p><p><b>{t.availability}:</b> {t.availabilityText}</p><p><b>{t.terms}:</b> {t.termsText}</p></div><div className="mt-8 flex flex-wrap gap-3"><Link href={`/${locale}/quote?product=${product.slug}`} className="btn-primary">{t.cta}</Link><Link href={`/${locale}/services`} className="btn-secondary">{t.services}</Link></div></div></div>{context&&<article className="mt-14 rounded-[2rem] border border-ink/8 bg-white p-7 md:p-9"><h2 className="text-2xl font-semibold">{t.commercial}</h2><p className="mt-4 max-w-4xl leading-8 text-ink/65">{context}</p></article>}<div className="mt-8 grid gap-5 md:grid-cols-3">{[[t.details,t.detailsText],[t.packaging,t.packagingText],[t.compliance,t.complianceText]].map(([title,text])=><article key={title} className="rounded-3xl border border-ink/8 bg-white p-6"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-ink/60">{text}</p></article>)}</div>{related.length>0&&<section className="mt-14"><h2 className="text-2xl font-semibold">{t.related}</h2><div className="mt-6 flex flex-wrap gap-3">{related.map(item=><Link key={item.slug} href={`/${locale}/products/${item.slug}`} className="btn-secondary">{item.names[locale]}</Link>)}</div></section>}</div></section>;
}
