import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { products } from "@/lib/data";
import { isLocale, localizeCountry } from "@/lib/i18n";
import { SITE_URL } from "@/lib/seo";

const copy={
  tr:{support:"Ticaret desteği",supportText:"tedarik, doğrulama, lojistik ve dokümantasyon.",availability:"Uygunluk",availabilityText:"üretici kapasitesine ve hedef ülke gereksinimlerine bağlıdır.",terms:"Ticari koşullar",termsText:"ihtiyaç değerlendirmesinden sonra sunulur.",cta:"Size özel teklif isteyin",details:"Tedarik kapsamı",detailsText:"Üretici araştırması, ürün ve belge kontrolü, teklif karşılaştırması ve sevkiyat planlaması ihtiyaca göre koordine edilir.",packaging:"Ambalaj ve sipariş",packagingText:"Ambalaj türü, minimum sipariş miktarı ve termin süresi üreticiye ve teknik gereksinimlere göre teyit edilir.",compliance:"Kalite ve uygunluk",complianceText:"Sertifika, test, etiketleme ve hedef ülke mevzuatı sipariş öncesinde ürün bazında değerlendirilmelidir.",related:"Benzer fırsatlar"},
  en:{support:"Trade support",supportText:"sourcing, verification, logistics and documentation.",availability:"Availability",availabilityText:"subject to producer capacity and destination requirements.",terms:"Commercial terms",termsText:"provided after requirement review.",cta:"Request a tailored quote",details:"Sourcing scope",detailsText:"Producer research, product and document checks, quotation comparison and shipment planning are coordinated to match the requirement.",packaging:"Packaging and orders",packagingText:"Packaging, minimum order quantity and lead time are confirmed according to the producer and technical specification.",compliance:"Quality and compliance",complianceText:"Certificates, testing, labeling and destination rules should be reviewed for the specific product before ordering.",related:"Related opportunities"},
  es:{support:"Apoyo comercial",supportText:"abastecimiento, verificación, logística y documentación.",availability:"Disponibilidad",availabilityText:"sujeta a capacidad del productor y requisitos del destino.",terms:"Condiciones comerciales",termsText:"se proporcionan tras revisar la necesidad.",cta:"Solicitar cotización personalizada",details:"Alcance de abastecimiento",detailsText:"La búsqueda de productores, revisión de producto y documentos, comparación de ofertas y planificación logística se coordinan según la necesidad.",packaging:"Embalaje y pedidos",packagingText:"Embalaje, pedido mínimo y plazo se confirman según productor y especificación técnica.",compliance:"Calidad y cumplimiento",complianceText:"Certificados, ensayos, etiquetado y normativa de destino deben evaluarse para cada producto antes del pedido.",related:"Oportunidades relacionadas"}
} as const;
const categories={tr:{Food:"Gıda",Agriculture:"Tarım",Machinery:"Makine",Seafood:"Deniz Ürünleri",Construction:"Yapı",Beverage:"İçecek",Automotive:"Otomotiv",Truck:"Kamyon",HeavyEquipment:"İş Makineleri"},en:{Food:"Food",Agriculture:"Agriculture",Machinery:"Machinery",Seafood:"Seafood",Construction:"Construction",Beverage:"Beverage",Automotive:"Automotive",Truck:"Truck",HeavyEquipment:"Heavy Equipment"},es:{Food:"Alimentos",Agriculture:"Agricultura",Machinery:"Maquinaria",Seafood:"Productos del mar",Construction:"Construcción",Beverage:"Bebidas",Automotive:"Automoción",Truck:"Camiones",HeavyEquipment:"Maquinaria Pesada"}} as const;

export default async function Page({params}:{params:Promise<{locale:string,slug:string}>}) {
  const {locale,slug}=await params;
  if(!isLocale(locale)) notFound();
  const product=products.find(x=>x.slug===slug);
  if(!product) notFound();
  const t=copy[locale],category=categories[locale][product.category as keyof typeof categories.en]||product.category;
  const canonical=`${SITE_URL}/${locale}/products/${slug}`;
  const image=product.image.startsWith("http")?product.image:`${SITE_URL}${product.image}`;
  const structuredData=[
    {"@context":"https://schema.org","@type":"Product",name:product.names[locale],description:product.desc[locale],image:[image],category,brand:{"@type":"Brand",name:"HKO Trade Hub"},countryOfOrigin:localizeCountry(product.origin,locale),url:canonical},
    {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"HKO Trade Hub",item:`${SITE_URL}/${locale}`},{"@type":"ListItem",position:2,name:locale==="tr"?"Ürünler":locale==="es"?"Productos":"Products",item:`${SITE_URL}/${locale}/products`},{"@type":"ListItem",position:3,name:product.names[locale],item:canonical}]},
  ];
  const related=products.filter(item=>item.slug!==slug&&(item.category===product.category||item.origin===product.origin)).slice(0,3);
  return <section className="section"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><div className="container-shell"><nav className="mb-8 text-sm text-ink/50"><Link href={`/${locale}`}>HKO Trade Hub</Link> / <Link href={`/${locale}/products`}>{locale==="tr"?"Ürünler":locale==="es"?"Productos":"Products"}</Link></nav><div className="grid gap-12 lg:grid-cols-2"><div className="relative min-h-[480px] overflow-hidden rounded-[2.5rem]"><Image src={product.image} alt={`${product.names[locale]} — ${localizeCountry(product.origin,locale)}`} fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/></div><div className="self-center"><p className="eyebrow">{category} · {localizeCountry(product.origin,locale)}</p><h1 className="heading">{product.names[locale]}</h1><p className="mt-6 text-lg leading-8 text-ink/60">{product.desc[locale]}</p><div className="mt-8 grid gap-3 rounded-3xl bg-sand p-6 text-sm"><p><b>{t.support}:</b> {t.supportText}</p><p><b>{t.availability}:</b> {t.availabilityText}</p><p><b>{t.terms}:</b> {t.termsText}</p></div><Link href={`/${locale}/quote?product=${product.slug}`} className="btn-primary mt-8">{t.cta}</Link></div></div><div className="mt-14 grid gap-5 md:grid-cols-3">{[[t.details,t.detailsText],[t.packaging,t.packagingText],[t.compliance,t.complianceText]].map(([title,text])=><article key={title} className="rounded-3xl border border-ink/8 bg-white p-6"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-ink/60">{text}</p></article>)}</div>{related.length>0&&<section className="mt-14"><h2 className="text-2xl font-semibold">{t.related}</h2><div className="mt-6 flex flex-wrap gap-3">{related.map(item=><Link key={item.slug} href={`/${locale}/products/${item.slug}`} className="btn-secondary">{item.names[locale]}</Link>)}</div></section>}</div></section>;
}

