export const products = [
 {slug:"turkish-sunflower-oil",category:"Food",origin:"Türkiye",image:"https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1200&q=80",names:{tr:"Türk Ayçiçek Yağı",en:"Turkish Sunflower Oil",es:"Aceite de Girasol Turco"},desc:{tr:"Perakende ve endüstriyel kullanım için farklı ambalaj seçenekleri.",en:"Multiple packaging options for retail and industrial use.",es:"Múltiples formatos para uso minorista e industrial."}},
 {slug:"chilean-walnuts",category:"Agriculture",origin:"Chile",image:"/chilean-walnuts.png",names:{tr:"Şili Cevizi",en:"Chilean Walnuts",es:"Nueces Chilenas"},desc:{tr:"İhracata uygun yüksek kaliteli kabuklu ve iç ceviz.",en:"Export-grade in-shell and shelled premium walnuts.",es:"Nueces premium con y sin cáscara para exportación."}},
 {slug:"industrial-machinery",category:"Machinery",origin:"Türkiye",image:"https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1200&q=80",names:{tr:"Endüstriyel Makineler",en:"Industrial Machinery",es:"Maquinaria Industrial"},desc:{tr:"Üretim, paketleme ve ağır sanayi için seçili çözümler.",en:"Selected solutions for manufacturing, packaging and heavy industry.",es:"Soluciones para manufactura, embalaje e industria pesada."}},
 {slug:"chilean-seafood",category:"Seafood",origin:"Chile",image:"https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1200&q=80",names:{tr:"Şili Deniz Ürünleri",en:"Chilean Seafood",es:"Productos del Mar de Chile"},desc:{tr:"Soğuk zincir standartlarına uygun somon ve deniz ürünleri.",en:"Salmon and seafood compliant with cold-chain standards.",es:"Salmón y mariscos bajo estándares de cadena de frío."}},
 {slug:"construction-materials",category:"Construction",origin:"Türkiye",image:"https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80",names:{tr:"Yapı Malzemeleri",en:"Construction Materials",es:"Materiales de Construcción"},desc:{tr:"Seramik, doğal taş, profil ve proje bazlı yapı ürünleri.",en:"Ceramics, natural stone, profiles and project-based supplies.",es:"Cerámica, piedra natural, perfiles y suministros para proyectos."}},
 {slug:"chilean-wine-solutions",category:"Beverage",origin:"Chile",image:"https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1200&q=80",names:{tr:"Şili İçecek Çözümleri",en:"Chilean Beverage Solutions",es:"Soluciones de Bebidas Chilenas"},desc:{tr:"Özel marka ve distribütörlük projeleri için üretici bağlantıları.",en:"Producer connections for private-label and distribution projects.",es:"Conexiones con productores para marca privada y distribución."}},
 {slug:"automotive-spare-parts",category:"Automotive",origin:"Türkiye",image:"/automotive-spare-parts.png",names:{tr:"Otomobil Yedek Parçaları",en:"Automotive Spare Parts",es:"Repuestos para Automóviles"},desc:{tr:"Binek araçlar için fren, süspansiyon, filtre ve motor bileşenleri.",en:"Brake, suspension, filtration and engine components for passenger vehicles.",es:"Componentes de freno, suspensión, filtración y motor para automóviles."}},
 {slug:"truck-spare-parts",category:"Truck",origin:"Türkiye",image:"/truck-spare-parts.png",names:{tr:"Kamyon Yedek Parçaları",en:"Truck Spare Parts",es:"Repuestos para Camiones"},desc:{tr:"Ağır ticari araçlar için fren, hava süspansiyonu ve aktarma parçaları.",en:"Braking, air-suspension and drivetrain parts for heavy commercial vehicles.",es:"Piezas de freno, suspensión neumática y transmisión para vehículos pesados."}},
 {slug:"heavy-machinery-spare-parts",category:"HeavyEquipment",origin:"Türkiye",image:"/heavy-machinery-spare-parts.png",names:{tr:"İş Makinesi Yedek Parçaları",en:"Heavy Machinery Spare Parts",es:"Repuestos para Maquinaria Pesada"},desc:{tr:"Ekskavatör ve iş makineleri için hidrolik, palet ve aşınma parçaları.",en:"Hydraulic, undercarriage and wear parts for excavators and heavy equipment.",es:"Piezas hidráulicas, de tren de rodaje y desgaste para maquinaria pesada."}}
];

export const posts = [
 {slug:"turkiye-chile-trade-guide",date:"2026-07-18",title:{tr:"Türkiye–Şili Ticaretine Başlangıç Rehberi",en:"Getting Started with Turkey–Chile Trade",es:"Guía para iniciar comercio Turquía–Chile"}},
 {slug:"supplier-verification",date:"2026-07-10",title:{tr:"Uluslararası Tedarikçi Nasıl Doğrulanır?",en:"How to Verify an International Supplier",es:"Cómo verificar un proveedor internacional"}},
 {slug:"logistics-checklist",date:"2026-06-28",title:{tr:"İhracat Lojistiği Kontrol Listesi",en:"Export Logistics Checklist",es:"Lista de control de logística de exportación"}}
];
