import Link from "next/link";
import { notFound } from "next/navigation";
import { posts } from "@/lib/data";
import { isLocale } from "@/lib/i18n";
import { SITE_URL } from "@/lib/seo";

const articles = {
  "turkiye-chile-trade-guide": {
    tr: { intro:"Türkiye ile Şili arasında ticarete başlamak; doğru ürün, mevzuat, maliyet ve iş ortağı kararlarını birlikte yönetmeyi gerektirir.", sections:[
      ["1. Ürünü ve hedef pazarı doğrulayın","GTİP kodunu, teknik özellikleri, hedef müşteri profilini ve rakip fiyatlarını netleştirin. Gıda, tarım ve sanayi ürünlerinde izinler ile etiketleme kuralları ürün bazında değişebilir."],
      ["2. Toplam maliyeti hesaplayın","Ürün bedeline navlun, sigorta, gümrük vergileri, liman masrafları, iç taşıma ve finansman maliyetlerini ekleyin. Teklifleri aynı Incoterms teslim şekli üzerinden karşılaştırın."],
      ["3. İş ortağını doğrulayın","Şirket kayıtlarını, üretim kapasitesini, kalite belgelerini, ihracat geçmişini ve banka bilgilerini kontrol edin. Numune veya pilot sipariş, büyük hacimli anlaşmadan önce riski azaltır."],
      ["4. Operasyon planını yazılı hale getirin","Teslim süresi, kalite toleransları, ödeme yöntemi, kontrol noktaları ve uyuşmazlık prosedürünü sözleşmede açıkça belirtin."],
    ], checklist:"Başlangıç kontrolü", items:["Ürün ve GTİP kodu","Hedef ülke mevzuatı","Toplam teslim maliyeti","Doğrulanmış alıcı veya tedarikçi","Yazılı teslim ve ödeme koşulları"]},
    en: { intro:"Starting trade between Turkey and Chile requires coordinated decisions on product fit, compliance, landed cost and counterparties.", sections:[
      ["1. Validate the product and target market","Confirm the HS code, specifications, customer profile and competing price levels. Permits and labeling rules vary by product, especially for food, agriculture and industrial goods."],
      ["2. Calculate landed cost","Add freight, insurance, duties, port charges, inland transport and financing to the product price. Compare quotations on the same Incoterms basis."],
      ["3. Verify the counterparty","Check company registration, capacity, quality certificates, export history and banking details. Samples or pilot orders reduce risk before a larger commitment."],
      ["4. Document the operating plan","State lead times, quality tolerances, payment method, inspection points and dispute procedures clearly in the contract."],
    ], checklist:"Start-up checklist", items:["Product and HS code","Destination compliance","Total landed cost","Verified buyer or supplier","Written delivery and payment terms"]},
    es: { intro:"Iniciar comercio entre Turquía y Chile exige coordinar decisiones sobre producto, normativa, costo total y contrapartes.", sections:[
      ["1. Valide el producto y el mercado","Confirme código arancelario, especificaciones, cliente objetivo y precios competidores. Los permisos y el etiquetado varían según el producto."],
      ["2. Calcule el costo puesto en destino","Sume flete, seguro, aranceles, gastos portuarios, transporte interno y financiación. Compare ofertas con el mismo Incoterm."],
      ["3. Verifique la contraparte","Revise registro mercantil, capacidad, certificados, historial exportador y datos bancarios. Una muestra o pedido piloto reduce el riesgo."],
      ["4. Documente el plan operativo","Defina plazos, tolerancias de calidad, pago, inspecciones y resolución de controversias en el contrato."],
    ], checklist:"Lista inicial", items:["Producto y código arancelario","Normativa de destino","Costo total","Comprador o proveedor verificado","Condiciones escritas de entrega y pago"]},
  },
  "supplier-verification": {
    tr:{intro:"Tedarikçi doğrulaması yalnızca bir internet araması değildir; şirketin hukuki, operasyonel ve ticari kapasitesini kanıtlarla değerlendirme sürecidir.",sections:[["Şirket kimliğini kontrol edin","Ticaret sicili, vergi numarası, adres, yetkili kişiler ve banka hesabı sahibinin aynı tüzel kişiliğe ait olduğunu doğrulayın."],["Üretim ve kalite kapasitesini inceleyin","Fabrika görüntüsü yerine güncel kapasite kayıtları, kalite belgeleri, test raporları ve ürün izlenebilirliği talep edin."],["Ticari geçmişi sorgulayın","İhracat yapılan ülkeler, müşteri referansları, geçmiş sevkiyatlar ve olası hukuki ihtilaflar hakkında belge isteyin."],["Ödemeyi aşamalı yönetin","Numune, üretim başlangıcı, bağımsız kontrol ve sevkiyat belgelerine bağlı ödeme aşamaları belirleyin."]],checklist:"Kırmızı bayraklar",items:["Kişisel banka hesabı talebi","Belge paylaşmaktan kaçınma","Gerçekçi olmayan düşük fiyat","Acele tam ödeme baskısı","Sözleşmedeki bilgilerin uyuşmaması"]},
    en:{intro:"Supplier verification is more than an online search; it is an evidence-based review of legal identity, operating capability and commercial reliability.",sections:[["Confirm the legal identity","Match registration, tax number, address, authorized representatives and bank beneficiary to the same legal entity."],["Review production and quality capacity","Request current capacity records, certificates, test reports and traceability evidence rather than relying on factory photos."],["Check commercial history","Ask for export markets, customer references, shipment history and disclosure of material disputes."],["Stage payments against evidence","Link payment milestones to samples, production start, independent inspection and shipping documents."]],checklist:"Warning signs",items:["Personal bank account","Refusal to share documents","Unrealistically low pricing","Pressure for immediate full payment","Conflicting company details"]},
    es:{intro:"Verificar un proveedor es una revisión documentada de su identidad legal, capacidad operativa y fiabilidad comercial.",sections:[["Confirme la identidad jurídica","Haga coincidir registro, identificación fiscal, dirección, representantes y beneficiario bancario."],["Revise capacidad y calidad","Solicite registros de capacidad, certificados, ensayos y trazabilidad en lugar de depender de fotografías."],["Compruebe el historial comercial","Pida mercados de exportación, referencias, envíos anteriores y controversias relevantes."],["Vincule pagos a evidencias","Relacione cada pago con muestras, producción, inspección independiente y documentos de embarque."]],checklist:"Señales de alerta",items:["Cuenta bancaria personal","Negativa a compartir documentos","Precio irrealmente bajo","Presión por pago total inmediato","Datos empresariales contradictorios"]},
  },
  "logistics-checklist": {
    tr:{intro:"İhracat lojistiğinde gecikmeler çoğunlukla ürün hazır olmadan önce netleştirilmeyen belge, taşıma ve teslim sorumluluklarından kaynaklanır.",sections:[["Sevkiyat öncesi","Ambalaj ölçülerini, brüt-net ağırlığı, yükleme tarihini, tehlikeli madde durumunu ve sıcaklık gereksinimini doğrulayın."],["Belgeler","Ticari fatura, çeki listesi, menşe belgesi, taşıma belgesi ve ürüne özgü sertifikalarda isim ve miktarların tutarlı olmasını sağlayın."],["Taşıma ve sigorta","Transit süreyi yalnızca limandan limana değil, kapıdan kapıya değerlendirin. Poliçenin kapsamını ve hasar bildirim süresini kontrol edin."],["Varış ve teslim","Gümrük müşavirine belgeleri önceden gönderin; terminal, ardiye ve iç taşıma planını gemi veya uçak varışından önce hazırlayın."]],checklist:"Sevkiyat dosyası",items:["Onaylı rezervasyon","Fatura ve çeki listesi","Menşe ve ürün belgeleri","Sigorta poliçesi","Varış gümrükleme planı"]},
    en:{intro:"Export logistics delays often begin with documents, transport requirements and delivery responsibilities left unclear before the cargo is ready.",sections:[["Before shipment","Confirm packaging dimensions, gross and net weight, loading date, dangerous-goods status and temperature requirements."],["Documents","Keep names, quantities and references consistent across invoice, packing list, origin certificate, transport document and product certificates."],["Transport and insurance","Assess door-to-door transit time, not only port-to-port time. Review policy coverage and claims notification deadlines."],["Arrival and delivery","Send documents to the customs broker in advance and plan terminal charges, storage and inland delivery before arrival."]],checklist:"Shipment file",items:["Confirmed booking","Invoice and packing list","Origin and product documents","Insurance policy","Arrival clearance plan"]},
    es:{intro:"Los retrasos logísticos suelen comenzar cuando documentos, transporte y responsabilidades no se definen antes de que la carga esté lista.",sections:[["Antes del embarque","Confirme embalaje, pesos, fecha de carga, mercancía peligrosa y requisitos de temperatura."],["Documentos","Mantenga nombres, cantidades y referencias coherentes en factura, lista de empaque, origen, transporte y certificados."],["Transporte y seguro","Evalúe el tránsito puerta a puerta. Revise cobertura y plazo de notificación de siniestros."],["Llegada y entrega","Envíe documentos al agente de aduanas y planifique terminal, almacenaje y transporte interno antes de la llegada."]],checklist:"Expediente de embarque",items:["Reserva confirmada","Factura y lista de empaque","Documentos de origen y producto","Póliza de seguro","Plan de despacho en destino"]},
  },
} as const;

export default async function Page({params}:{params:Promise<{locale:string,slug:string}>}) {
  const {locale,slug}=await params;
  if(!isLocale(locale)) notFound();
  const post=posts.find(x=>x.slug===slug);
  const article=articles[slug as keyof typeof articles]?.[locale];
  if(!post||!article) notFound();
  const canonical=`${SITE_URL}/${locale}/blog/${slug}`;
  const structuredData=[
    {"@context":"https://schema.org","@type":"Article",headline:post.title[locale],datePublished:post.date,dateModified:"2026-08-22",author:{"@type":"Organization",name:"HKO Trade Hub"},publisher:{"@type":"Organization",name:"HKO Trade Hub",logo:{"@type":"ImageObject",url:`${SITE_URL}/hko-trade-hub-logo.png`}},mainEntityOfPage:canonical,inLanguage:locale},
    {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"HKO Trade Hub",item:`${SITE_URL}/${locale}`},{"@type":"ListItem",position:2,name:"Blog",item:`${SITE_URL}/${locale}/blog`},{"@type":"ListItem",position:3,name:post.title[locale],item:canonical}]},
  ];
  return <article className="section"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><div className="container-shell max-w-3xl"><nav className="mb-7 text-sm text-ink/50"><Link href={`/${locale}`}>HKO Trade Hub</Link> / <Link href={`/${locale}/blog`}>Blog</Link></nav><p className="eyebrow">HKO Blog · {post.date}</p><h1 className="heading">{post.title[locale]}</h1><p className="mt-7 text-xl leading-9 text-ink/70">{article.intro}</p><div className="mt-10 space-y-9">{article.sections.map(([heading,text])=><section key={heading}><h2 className="text-2xl font-semibold">{heading}</h2><p className="mt-3 text-lg leading-9 text-ink/70">{text}</p></section>)}</div><aside className="mt-10 rounded-3xl bg-sand p-7"><h2 className="text-xl font-semibold">{article.checklist}</h2><ul className="mt-4 grid gap-2 text-ink/70">{article.items.map(item=><li key={item}>✓ {item}</li>)}</ul></aside><div className="mt-10 border-t border-ink/10 pt-7"><Link className="btn-primary" href={`/${locale}/quote`}>{locale==="tr"?"Ticaret ihtiyacınızı paylaşın":locale==="es"?"Comparta su necesidad comercial":"Discuss your trade requirement"}</Link></div></div></article>;
}
